name: Vercel Continuous Integration

on:
  push:
    branches: [main, develop, feature/*, refactor, hotfix/*]

  pull_request:
    branches: [main, develop, feature/*, refactor, hotfix/*]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
      - run: npm install
